import { db } from "@workspace/db";
import { productsTable, categoriesTable } from "@workspace/db";

const categories = [
  {
    name: "Vibromasseurs",
    slug: "vibrators",
    description: "Vibromasseurs et stimulateurs pour tous les goûts",
    imageUrl: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=600&q=80",
  },
  {
    name: "Godes & Dildos",
    slug: "dildos",
    description: "Large sélection de godes réalistes et fantaisie de toutes tailles",
    imageUrl: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&q=80",
  },
  {
    name: "Poupées Sexuelles",
    slug: "sex-dolls",
    description: "Poupées sexuelles homme et femme de haute qualité",
    imageUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&q=80",
  },
  {
    name: "Stimulants & Pilules",
    slug: "pills",
    description: "Viagra, stimulants naturels et aphrodisiaques",
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=80",
  },
  {
    name: "BDSM & Accessoires",
    slug: "bdsm",
    description: "Menottes, fouets, cravaches et jeux de pouvoir",
    imageUrl: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=600&q=80",
  },
  {
    name: "Lingerie & Costumes",
    slug: "lingerie",
    description: "Lingerie sexy, costumes érotiques et tenues coquines",
    imageUrl: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&q=80",
  },
];

const products = [
  // VIBRATORS
  {
    name: "Lelo Sona 2 Cruise – Stimulateur Clitoridien",
    description: "Le Lelo Sona 2 Cruise utilise la technologie des ondes soniques pour stimuler tout le clitoris, pas seulement la surface. 12 modes de stimulation, étanche, silicone médical ultrasoft. Connu comme le meilleur stimulateur clitoridien au monde.",
    price: "149.99",
    discountPrice: "119.99",
    category: "Vibromasseurs",
    categorySlug: "vibrators",
    imageUrl: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600&q=80"],
    colors: JSON.stringify(["Rose", "Corail", "Turquoise", "Noir"]),
    sizes: JSON.stringify([]),
    inStock: true,
    featured: true,
    rating: "4.9",
    reviewCount: 847,
    brand: "LELO",
    material: "Silicone médical",
    length: "7.5 cm",
    diameter: "3.5 cm",
    tags: JSON.stringify(["clitoridien", "ondes soniques", "bestseller", "rechargeable"]),
  },
  {
    name: "Vibromasseur Rabbit We-Vibe Rave 2",
    description: "Le We-Vibe Rave 2 combine stimulation G-spot et clitoris simultanément. Forme ergonomique innovante, 10 modes de vibration, contrôlable via l'app We-Connect depuis n'importe où dans le monde. USB rechargeable.",
    price: "179.99",
    discountPrice: "144.99",
    category: "Vibromasseurs",
    categorySlug: "vibrators",
    imageUrl: "https://images.unsplash.com/photo-1577538928305-3807c3993047?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1577538928305-3807c3993047?w=600&q=80"],
    colors: JSON.stringify(["Violet", "Bleu Nuit", "Bordeaux"]),
    sizes: JSON.stringify([]),
    inStock: true,
    featured: true,
    rating: "4.8",
    reviewCount: 623,
    brand: "We-Vibe",
    material: "Silicone premium",
    length: "18 cm",
    diameter: "3.8 cm",
    tags: JSON.stringify(["rabbit", "point G", "double stimulation", "app connectée"]),
  },
  {
    name: "Satisfyer Pro 2 – Stimulateur Clitoridien par Succion",
    description: "Le Satisfyer Pro 2 révolutionne le plaisir féminin avec sa technologie de pression d'air contactless. 11 niveaux d'intensité, étanche, silicone médical. Des millions de femmes satisfaites dans le monde entier.",
    price: "59.99",
    discountPrice: "44.99",
    category: "Vibromasseurs",
    categorySlug: "vibrators",
    imageUrl: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&q=80"],
    colors: JSON.stringify(["Blanc", "Rose", "Noir", "Doré"]),
    sizes: JSON.stringify([]),
    inStock: true,
    featured: true,
    rating: "4.7",
    reviewCount: 2145,
    brand: "Satisfyer",
    material: "Silicone ABS",
    length: "16 cm",
    diameter: "4 cm",
    tags: JSON.stringify(["succion", "clitoridien", "bestseller", "étanche"]),
  },
  {
    name: "Magic Wand Vibromasseur – Hitachi Pro",
    description: "L'iconique Magic Wand dans sa version Pro rechargeable. Puissance légendaire, 4 vitesses et 4 modes de vibration, silicone de qualité médicale, parfait pour massages relaxants et stimulation intense.",
    price: "89.99",
    discountPrice: "69.99",
    category: "Vibromasseurs",
    categorySlug: "vibrators",
    imageUrl: "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=600&q=80"],
    colors: JSON.stringify(["Blanc/Gris", "Noir", "Violet"]),
    sizes: JSON.stringify([]),
    inStock: true,
    featured: false,
    rating: "4.8",
    reviewCount: 1892,
    brand: "Hitachi",
    material: "Silicone médical",
    length: "30 cm",
    diameter: "5.5 cm",
    tags: JSON.stringify(["wand", "puissant", "classique", "massage"]),
  },
  {
    name: "Vibromasseur OhMyBod Club Vibe 3.Oh Hero",
    description: "Le premier vibromasseur qui répond à la musique! S'active avec les basses musicales en discothèque ou via Bluetooth. Design discret portable, modes multiples, parfait pour aventures publiques.",
    price: "99.99",
    discountPrice: "79.99",
    category: "Vibromasseurs",
    categorySlug: "vibrators",
    imageUrl: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&q=80"],
    colors: JSON.stringify(["Noir", "Rose Fuchsia", "Violet"]),
    sizes: JSON.stringify([]),
    inStock: true,
    featured: false,
    rating: "4.5",
    reviewCount: 312,
    brand: "OhMyBod",
    material: "Silicone",
    length: "15 cm",
    diameter: "3 cm",
    tags: JSON.stringify(["musique", "bluetooth", "discret", "portable"]),
  },

  // DILDOS
  {
    name: "Gode Réaliste Doc Johnson American Whopper 9\"",
    description: "Gode réaliste en PVC de qualité supérieure, veinures prononcées pour une sensation authentique. Ventouse puissante pour mains libres, compatible avec harnais. 23 cm de longueur totale, 5 cm de diamètre.",
    price: "49.99",
    discountPrice: "39.99",
    category: "Godes & Dildos",
    categorySlug: "dildos",
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80"],
    colors: JSON.stringify(["Chair", "Brun Caramel", "Chocolat Foncé", "Noir Ébène"]),
    sizes: JSON.stringify(["Moyen 7\"", "Grand 9\"", "XL 12\""]),
    inStock: true,
    featured: true,
    rating: "4.6",
    reviewCount: 489,
    brand: "Doc Johnson",
    material: "PVC hypoallergénique",
    length: "23 cm",
    diameter: "5 cm",
    tags: JSON.stringify(["réaliste", "ventouse", "harnais", "grande taille"]),
  },
  {
    name: "Gode en Verre Borosilicate Luxe G-Spot",
    description: "Gode artisanal en verre borosilicate premium, compatible températures chaud/froid pour sensations uniques. Design ergonomique G-spot, surface lisse pour glisse parfaite. Absolument magnifique.",
    price: "69.99",
    discountPrice: "54.99",
    category: "Godes & Dildos",
    categorySlug: "dildos",
    imageUrl: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600&q=80"],
    colors: JSON.stringify(["Transparent", "Bleu Cobalt", "Violet Améthyste", "Rose"]),
    sizes: JSON.stringify(["Small", "Medium", "Large"]),
    inStock: true,
    featured: true,
    rating: "4.8",
    reviewCount: 267,
    brand: "Icicles",
    material: "Verre borosilicate",
    length: "19 cm",
    diameter: "3.5 cm",
    tags: JSON.stringify(["verre", "point G", "luxe", "température"]),
  },
  {
    name: "Double Penetration Dildo Fun Factory ShareVibe",
    description: "Gode double pour couples ou solo anal+vaginal simultané. Silicone premium corps entier, 6 modes vibrants dans chaque extrémité, rechargeable USB. Expérience de plaisir total.",
    price: "139.99",
    discountPrice: "109.99",
    category: "Godes & Dildos",
    categorySlug: "dildos",
    imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80"],
    colors: JSON.stringify(["Noir", "Violet", "Bleu"]),
    sizes: JSON.stringify([]),
    inStock: true,
    featured: false,
    rating: "4.7",
    reviewCount: 198,
    brand: "Fun Factory",
    material: "Silicone premium",
    length: "44 cm total",
    diameter: "3.8 cm",
    tags: JSON.stringify(["double", "couples", "vibrant", "rechargeable"]),
  },
  {
    name: "Gode Géant XXXL Bad Dragon – Fantasy Dragon",
    description: "Pour amateurs de tailles extrêmes! Gode fantaisie ultra-réaliste en silicone de platine, dimensions XXL impressionnantes. Disponible en 4 tailles (S/M/L/XL) et multiples coloris fantaisie uniques.",
    price: "119.99",
    discountPrice: "95.99",
    category: "Godes & Dildos",
    categorySlug: "dildos",
    imageUrl: "https://images.unsplash.com/photo-1569982175971-d92b01cf8694?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1569982175971-d92b01cf8694?w=600&q=80"],
    colors: JSON.stringify(["Violet Galaxie", "Bleu Dragon", "Rouge Feu", "Arc-en-Ciel", "Vert Émeraude"]),
    sizes: JSON.stringify(["Small (16cm)", "Medium (22cm)", "Large (28cm)", "XL (34cm)"]),
    inStock: true,
    featured: false,
    rating: "4.9",
    reviewCount: 734,
    brand: "Bad Dragon",
    material: "Silicone platine",
    length: "22 cm (Medium)",
    diameter: "6.5 cm (Medium)",
    tags: JSON.stringify(["fantaisie", "XXL", "silicone platine", "fantasy"]),
  },

  // SEX DOLLS
  {
    name: "Poupée Sexuelle TPE Premium – Femme Asiatique 158cm",
    description: "Poupée sexuelle ultra-réaliste en TPE (élastomère thermoplastique) grade médical. Corps entier 158cm, peau douce et réaliste, squelette articulé en acier inoxydable, 3 orifices fonctionnels. Livraison discrète. Cheveux et maquillage personnalisables.",
    price: "1899.99",
    discountPrice: "1499.99",
    category: "Poupées Sexuelles",
    categorySlug: "sex-dolls",
    imageUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&q=80"],
    colors: JSON.stringify(["Teint Asiatique Claire", "Teint Naturel", "Teint Bronzé", "Teint Ébène"]),
    sizes: JSON.stringify(["158cm - 35kg", "165cm - 40kg"]),
    inStock: true,
    featured: true,
    rating: "4.8",
    reviewCount: 156,
    brand: "WM Dolls",
    material: "TPE grade médical",
    length: "158 cm",
    diameter: null,
    tags: JSON.stringify(["TPE", "réaliste", "corps entier", "squelette articulé", "3 orifices"]),
  },
  {
    name: "Poupée Sexuelle Silicone – Femme Européenne 165cm",
    description: "Poupée en silicone platine de très haute qualité, peau encore plus réaliste que TPE, résistante à la chaleur et hypoallergénique. Visage sculpté par artiste, corps parfaitement proportionné 165cm. La meilleure qualité disponible.",
    price: "3499.99",
    discountPrice: "2799.99",
    category: "Poupées Sexuelles",
    categorySlug: "sex-dolls",
    imageUrl: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=600&q=80"],
    colors: JSON.stringify(["Teint Caucasien", "Teint Méditerranéen", "Teint Latino"]),
    sizes: JSON.stringify(["165cm - 42kg", "170cm - 45kg"]),
    inStock: true,
    featured: true,
    rating: "4.9",
    reviewCount: 89,
    brand: "RealDoll",
    material: "Silicone platine",
    length: "165 cm",
    diameter: null,
    tags: JSON.stringify(["silicone", "premium", "ultra-réaliste", "art sculpture"]),
  },
  {
    name: "Torse Masculin avec Pénis Géant – Homme Musclé",
    description: "Torse masculin réaliste en silicone pour les femmes et hommes appréciant les corps masculins. Pénis réaliste 22cm bien formé, pectoraux musclés, abdos définis. Silicone premium corps réaliste.",
    price: "299.99",
    discountPrice: "239.99",
    category: "Poupées Sexuelles",
    categorySlug: "sex-dolls",
    imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80"],
    colors: JSON.stringify(["Chair Blanc", "Beige Méditerranéen", "Caramel", "Ébène"]),
    sizes: JSON.stringify([]),
    inStock: true,
    featured: false,
    rating: "4.7",
    reviewCount: 243,
    brand: "Fleshlight",
    material: "SuperSkin™ silicone",
    length: "45 cm",
    diameter: null,
    tags: JSON.stringify(["masculin", "torse", "réaliste", "silicone"]),
  },
  {
    name: "Mini Poupée Gonflable Premium – Femme Noire 140cm",
    description: "Poupée gonflable de nouvelle génération avec visage en latex souple ultra-réaliste et orifices en TPE. Corps 140cm léger et discret à ranger. Parfait pour voyageurs et espaces restreints. Accessoires inclus.",
    price: "189.99",
    discountPrice: "149.99",
    category: "Poupées Sexuelles",
    categorySlug: "sex-dolls",
    imageUrl: "https://images.unsplash.com/photo-1596495578065-6e0763fa1178?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1596495578065-6e0763fa1178?w=600&q=80"],
    colors: JSON.stringify(["Teint Ébène", "Teint Marron Caramel", "Teint Chocolat"]),
    sizes: JSON.stringify(["140cm"]),
    inStock: true,
    featured: false,
    rating: "4.3",
    reviewCount: 312,
    brand: "Fantasy",
    material: "Latex premium + TPE orifices",
    length: "140 cm",
    diameter: null,
    tags: JSON.stringify(["gonflable", "légère", "discrète", "portable"]),
  },

  // PILLS
  {
    name: "Viagra Générique Sildenafil 100mg – 12 comprimés",
    description: "Sildenafil citrate 100mg (équivalent générique Viagra), action en 30 minutes, efficacité 4-6 heures. Laboratoire certifié, ingrédients purs. Pour dysfonction érectile et amélioration des performances. Discrétion garantie.",
    price: "79.99",
    discountPrice: "59.99",
    category: "Stimulants & Pilules",
    categorySlug: "pills",
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=80"],
    colors: JSON.stringify([]),
    sizes: JSON.stringify(["50mg x12", "100mg x12", "100mg x24", "100mg x48"]),
    inStock: true,
    featured: true,
    rating: "4.7",
    reviewCount: 1243,
    brand: "GenericPharma",
    material: null,
    length: null,
    diameter: null,
    tags: JSON.stringify(["sildenafil", "érection", "performance", "générique"]),
  },
  {
    name: "Cialis Générique Tadalafil 20mg – Le Weekend",
    description: "Tadalafil 20mg – Le fameux médicament du weekend actif 36 heures! Discret, efficace, permet spontanéité totale. Disponible en comprimés pelliculés ou gélules. Effet jusqu'à 1.5 jours.",
    price: "89.99",
    discountPrice: "69.99",
    category: "Stimulants & Pilules",
    categorySlug: "pills",
    imageUrl: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=600&q=80"],
    colors: JSON.stringify([]),
    sizes: JSON.stringify(["10mg x10", "20mg x10", "20mg x20"]),
    inStock: true,
    featured: true,
    rating: "4.8",
    reviewCount: 987,
    brand: "GenericPharma",
    material: null,
    length: null,
    diameter: null,
    tags: JSON.stringify(["tadalafil", "36 heures", "weekend", "spontané"]),
  },
  {
    name: "Supplément Naturel Boost Testostérone – TestoMax",
    description: "Complexe naturel pour booster testostérone et libido: Tribulus Terrestris, Maca du Pérou, Ginseng Rouge, Zinc, Vitamine D3. Résultats en 2-4 semaines. 60 gélules vegan.",
    price: "49.99",
    discountPrice: "39.99",
    category: "Stimulants & Pilules",
    categorySlug: "pills",
    imageUrl: "https://images.unsplash.com/photo-1576671081837-49000212a370?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1576671081837-49000212a370?w=600&q=80"],
    colors: JSON.stringify([]),
    sizes: JSON.stringify(["60 gélules", "120 gélules"]),
    inStock: true,
    featured: false,
    rating: "4.5",
    reviewCount: 567,
    brand: "TestoMax",
    material: null,
    length: null,
    diameter: null,
    tags: JSON.stringify(["naturel", "testostérone", "libido", "vegan"]),
  },
  {
    name: "Aphrodisiaque Féminin – HerBliss Drops",
    description: "Gouttes aphrodisiaques liquides pour femmes à base d'extraits naturels de Damiana, Maca Rouge et L-Arginine. Augmente excitation et sensibilité. Inodore, insipide, se mélange à toutes boissons. 30ml.",
    price: "44.99",
    discountPrice: "34.99",
    category: "Stimulants & Pilules",
    categorySlug: "pills",
    imageUrl: "https://images.unsplash.com/photo-1550572017-4fcdbb59cc32?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1550572017-4fcdbb59cc32?w=600&q=80"],
    colors: JSON.stringify([]),
    sizes: JSON.stringify(["30ml", "60ml"]),
    inStock: true,
    featured: false,
    rating: "4.4",
    reviewCount: 423,
    brand: "HerBliss",
    material: null,
    length: null,
    diameter: null,
    tags: JSON.stringify(["féminin", "aphrodisiaque", "naturel", "liquide"]),
  },
  {
    name: "Spray Retardant Climax Control",
    description: "Spray lidocaïne 10% pour hommes souhaitant prolonger leurs performances. Application localisée, absorption rapide, aucune transfert à la partenaire. Flacon 20ml discret et portable.",
    price: "34.99",
    discountPrice: "27.99",
    category: "Stimulants & Pilules",
    categorySlug: "pills",
    imageUrl: "https://images.unsplash.com/photo-1563281577-a7be47e20db9?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1563281577-a7be47e20db9?w=600&q=80"],
    colors: JSON.stringify([]),
    sizes: JSON.stringify(["20ml", "40ml"]),
    inStock: true,
    featured: false,
    rating: "4.3",
    reviewCount: 334,
    brand: "ClimaxControl",
    material: null,
    length: null,
    diameter: null,
    tags: JSON.stringify(["retardant", "lidocaïne", "performance", "spray"]),
  },

  // BDSM
  {
    name: "Kit BDSM Débutant 10 Pièces – Shibari Collection",
    description: "Kit complet pour initiation BDSM: menottes en velours rose, bandeau yeux, fouet à lanières douces, baguette en cuir, pinces tétons ajustables, corde shibari 5m, baillon boule, collier avec laisse. Tout pour explorer!",
    price: "89.99",
    discountPrice: "69.99",
    category: "BDSM & Accessoires",
    categorySlug: "bdsm",
    imageUrl: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=600&q=80"],
    colors: JSON.stringify(["Noir/Rose", "Noir/Rouge", "Noir/Violet"]),
    sizes: JSON.stringify([]),
    inStock: true,
    featured: true,
    rating: "4.7",
    reviewCount: 445,
    brand: "Shibari",
    material: "Velours, cuir vegan, corde coton",
    length: null,
    diameter: null,
    tags: JSON.stringify(["kit", "débutant", "menottes", "fouet", "shibari"]),
  },
  {
    name: "Menottes Métalliques de Luxe avec Fourrure",
    description: "Menottes en acier inoxydable poli avec garniture fourrure douce, serrure à clé de sécurité, mécanisme de libération rapide. Stylées et fonctionnelles, ajustables. 2 clés incluses.",
    price: "44.99",
    discountPrice: "35.99",
    category: "BDSM & Accessoires",
    categorySlug: "bdsm",
    imageUrl: "https://images.unsplash.com/photo-1552960562-daf630e9278b?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1552960562-daf630e9278b?w=600&q=80"],
    colors: JSON.stringify(["Argent/Blanc", "Or Rose/Rose", "Noir/Noir"]),
    sizes: JSON.stringify([]),
    inStock: true,
    featured: false,
    rating: "4.6",
    reviewCount: 287,
    brand: "Bound",
    material: "Acier inoxydable + fourrure",
    length: null,
    diameter: null,
    tags: JSON.stringify(["menottes", "métal", "fourrure", "clé", "luxe"]),
  },
  {
    name: "Cravache en Cuir Véritable Premium",
    description: "Cravache artisanale en cuir véritable pleine fleur, poignée tressée ergonomique, lanière plate précise. Idéale pour jeux de discipline, du doux picotement à la frappe vive. 65cm totale.",
    price: "59.99",
    discountPrice: "47.99",
    category: "BDSM & Accessoires",
    categorySlug: "bdsm",
    imageUrl: "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=600&q=80"],
    colors: JSON.stringify(["Noir", "Bordeaux", "Brun Cognac"]),
    sizes: JSON.stringify(["50cm", "65cm", "80cm"]),
    inStock: true,
    featured: false,
    rating: "4.8",
    reviewCount: 178,
    brand: "CuirArt",
    material: "Cuir véritable pleine fleur",
    length: "65 cm",
    diameter: null,
    tags: JSON.stringify(["cravache", "cuir", "discipline", "artisanal"]),
  },

  // LINGERIE
  {
    name: "Ensemble Lingerie Dentelle Bustier + String – Rouge Passion",
    description: "Ensemble de lingerie ultra-sexy en dentelle de Calais: bustier push-up avec balconnet, string assorti et jarretelles. Disponible du bonnet A au F. S à XXXL. Matière douce et confortable toute la journée.",
    price: "69.99",
    discountPrice: "54.99",
    category: "Lingerie & Costumes",
    categorySlug: "lingerie",
    imageUrl: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&q=80"],
    colors: JSON.stringify(["Rouge", "Noir", "Bordeaux", "Rose Nude", "Blanc Ivoire"]),
    sizes: JSON.stringify(["S (36)", "M (38)", "L (40)", "XL (42)", "XXL (44)", "XXXL (46)"]),
    inStock: true,
    featured: true,
    rating: "4.7",
    reviewCount: 678,
    brand: "LouisetteParis",
    material: "Dentelle de Calais + lycra",
    length: null,
    diameter: null,
    tags: JSON.stringify(["bustier", "dentelle", "push-up", "ensemble", "rouge"]),
  },
  {
    name: "Body Transparent Mesh avec Ouvertures Stratégiques",
    description: "Body en résille transparente avec ouvertures dorsale et frontale. Fermeture crochet entrejambe, bretelles réglables. Look provocateur garantie. Disponible plusieurs coloris, tailles S à XXL.",
    price: "44.99",
    discountPrice: "34.99",
    category: "Lingerie & Costumes",
    categorySlug: "lingerie",
    imageUrl: "https://images.unsplash.com/photo-1554568218-0f1715e72254?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1554568218-0f1715e72254?w=600&q=80"],
    colors: JSON.stringify(["Noir", "Rouge", "Blanc", "Rose"]),
    sizes: JSON.stringify(["S", "M", "L", "XL", "XXL"]),
    inStock: true,
    featured: false,
    rating: "4.5",
    reviewCount: 389,
    brand: "Esclave",
    material: "Résille nylon + spandex",
    length: null,
    diameter: null,
    tags: JSON.stringify(["body", "transparent", "mesh", "sexy", "ouvertures"]),
  },
  {
    name: "Costume Infirmière Coquine – Kit Complet",
    description: "Costume infirmière ultra-court: robe blanche avec croix rouge, tablier, charlotte, stéthoscope déco, bas résille blancs, serre-poignets. Fermeture éclair dos. Tailles XS à XXL.",
    price: "54.99",
    discountPrice: "42.99",
    category: "Lingerie & Costumes",
    categorySlug: "lingerie",
    imageUrl: "https://images.unsplash.com/photo-1559181567-c3190bbd40b4?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1559181567-c3190bbd40b4?w=600&q=80"],
    colors: JSON.stringify(["Blanc/Rouge", "Noir/Rouge"]),
    sizes: JSON.stringify(["XS", "S", "M", "L", "XL", "XXL"]),
    inStock: true,
    featured: false,
    rating: "4.4",
    reviewCount: 512,
    brand: "RolPlay",
    material: "Polyester satiné",
    length: null,
    diameter: null,
    tags: JSON.stringify(["costume", "infirmière", "roleplay", "kit complet"]),
  },
  {
    name: "Corset Satin Bustier Vintage – Lacets au Dos",
    description: "Corset authentique en satin avec baleines en acier, lacets de serrage dans le dos pour taille de guêpe parfaite. Couture renforcée, qualité couturier. Idéal soirée ou chambre à coucher.",
    price: "84.99",
    discountPrice: "67.99",
    category: "Lingerie & Costumes",
    categorySlug: "lingerie",
    imageUrl: "https://images.unsplash.com/photo-1568252542512-9fe8fe9c87bb?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1568252542512-9fe8fe9c87bb?w=600&q=80"],
    colors: JSON.stringify(["Noir", "Rouge", "Bordeaux", "Violet Royal", "Blanc Ivoire", "Rose Champagne"]),
    sizes: JSON.stringify(["XS (32)", "S (34)", "M (36)", "L (38)", "XL (40)", "XXL (42)"]),
    inStock: true,
    featured: true,
    rating: "4.6",
    reviewCount: 334,
    brand: "CorsetCouture",
    material: "Satin + baleines acier",
    length: null,
    diameter: null,
    tags: JSON.stringify(["corset", "satin", "lacets", "taille guêpe", "vintage"]),
  },
];

async function seed() {
  console.log("Seeding categories...");
  await db.delete(categoriesTable);
  await db.insert(categoriesTable).values(categories);
  console.log(`Inserted ${categories.length} categories`);

  console.log("Seeding products...");
  await db.delete(productsTable);
  for (const product of products) {
    await db.insert(productsTable).values({
      ...product,
      colors: product.colors ? JSON.parse(product.colors) : [],
      sizes: product.sizes ? JSON.parse(product.sizes) : [],
      tags: product.tags ? JSON.parse(product.tags) : [],
    } as any);
  }
  console.log(`Inserted ${products.length} products`);
  console.log("Done!");
}

seed().catch(console.error);
